version: '3'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=developer
      - DATABASE_PASSWORD=developer
      - DATABASE_NAME=bookstore
    volumes:
      - ./app:/app/app
    
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer  
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "8085:80"
    depends_on:
      - mysql
